/**
 * Shared building blocks for every follow-up generator (conversation-followup,
 * question-followup) and for the main agent's guardrails.
 *
 * Born out of a real incident: the follow-up model INVENTED a "30 NIS first-visit
 * discount code" to win back a customer who declined on price. Follow-ups are
 * generated by a small model with a goal-seeking prompt ("bring them back to
 * book") — without hard rules it will fabricate incentives. These rules are
 * appended to every follow-up prompt verbatim.
 */

/** Hard rules for anything the business says proactively to a customer. */
export const FOLLOWUP_HARD_RULES =
  "חוקים קשיחים שאסור להפר בשום מצב: " +
  "אסור להמציא או להציע הנחות, מבצעים, קודי קופון, מחירים מיוחדים או הטבות מכל סוג — גם לא כדי לשכנע לקוח שאמר שיקר לו. " +
  "אסור להבטיח שום דבר שלא נאמר במפורש בשיחה עצמה (זמינות, מתנות, יוצאים מן הכלל). " +
  "אם ללקוח יקר — מותר להבין ולהשאיר דלת פתוחה, לא להציע פיצוי. " +
  "המחירים והשירותים היחידים שקיימים הם אלה שהוזכרו בשיחה.";

/**
 * "Now" line for time-aware follow-ups: the generator must know the current
 * Israel time so it never offers a slot that already passed.
 */
export function nowLineIsrael(): string {
  const now = new Date().toLocaleString("he-IL", {
    weekday: "long", year: "numeric", month: "long", day: "numeric",
    hour: "2-digit", minute: "2-digit", hour12: false, timeZone: "Asia/Jerusalem",
  });
  return `התאריך והשעה כרגע: ${now} (שעון ישראל).`;
}

/**
 * True when a "name" is actually a phone number (digits, +, spaces, dashes) —
 * some WhatsApp profiles have no name and the pushname arrives as the number.
 * Never address a customer by their phone number; omit the name instead.
 */
export function isPhoneLikeName(name: string | null | undefined): boolean {
  if (!name) return true;
  const stripped = name.replace(/[\s+\-().]/g, "");
  if (!stripped) return true;
  const digits = stripped.replace(/\D/g, "");
  // Mostly digits and long enough to be a phone number → phone-like.
  return digits.length >= 7 && digits.length / stripped.length > 0.8;
}

/**
 * Despite "return only the message itself, no preamble" in the prompt, the
 * follow-up model sometimes prefaces its answer with a meta-description of
 * what it's about to write, e.g. "הודעה טבעית שמזמינה את X לענות בעדינות:\n\n
 * <actual message>" — and that whole thing gets sent to the real customer
 * verbatim. Two confirmed incidents (2026-07-18, 2026-08-02) both had the
 * actual line as the LAST blank-line-separated paragraph, so take that; if
 * even the last paragraph still reads like meta-commentary, refuse it rather
 * than risk sending it (the caller falls back to a safe canned line).
 */
const PREAMBLE_MARKER_RE = /^(הודעה|אני רואה|הודעת ה)/;
export function stripFollowupPreamble(text: string): string | null {
  const paragraphs = text.split(/\n{2,}/).map(p => p.trim()).filter(Boolean);
  const last = paragraphs[paragraphs.length - 1] ?? text.trim();
  if (PREAMBLE_MARKER_RE.test(last)) return null;
  return last;
}
