import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();
const biz = await prisma.business.findFirst({ where: { name: "dominant" }, select: { id: true, bookingHorizonDays: true } });
console.log("business horizon:", biz.bookingHorizonDays);
const b = await prisma.staff.findFirst({ where: { businessId: biz.id, name: { contains: "בוחבוט" } }, select: { id: true, name: true, isAvailable: true, settings: true } });
console.log("\nבוחבוט:", b.id, "available:", b.isAvailable, "settings:", b.settings);
const ss = await prisma.staffService.findMany({ where: { staffId: b.id }, include: { service: { select: { id: true, name: true, durationMinutes: true, isVisible: true } } } });
console.log("\nStaffService rows for בוחבוט:");
for (const r of ss) console.log(`  service ${r.service.id.slice(0,8)} "${r.service.name}" dur:${r.customDuration ?? r.service.durationMinutes} visible:${r.service.isVisible}`);
const dow = new Date("2026-07-01T00:00:00.000Z").getUTCDay();
console.log("\n2026-07-01 day-of-week (0=Sun):", dow);
const sched = await prisma.staffSchedule.findMany({ where: { staffId: b.id }, select: { dayOfWeek: true, isWorking: true, slots: true } });
console.log("\nWeekly schedule:");
for (const s of sched.sort((a,b)=>a.dayOfWeek-b.dayOfWeek)) console.log(`  day ${s.dayOfWeek}: working:${s.isWorking} slots:${s.slots}`);
const ov = await prisma.staffScheduleOverride.findUnique({ where: { staffId_date: { staffId: b.id, date: new Date("2026-07-01T00:00:00.000Z") } } });
console.log("\nOverride for 2026-07-01:", ov ? `isWorking:${ov.isWorking} slots:${ov.slots}` : "none");
const appts = await prisma.appointment.findMany({ where: { staffId: b.id, date: new Date("2026-07-01T00:00:00.000Z"), status: { in: ["pending","confirmed"] } }, select: { startTime: true, endTime: true, status: true } });
console.log("\nBooked appts on 2026-07-01:", appts.length);
for (const a of appts) console.log(`  ${a.startTime}-${a.endTime} ${a.status}`);
await prisma.$disconnect();
